#!/usr/bin/env bash
# Flatten the skill into a single self-contained prompt for agents that
# have no progressive disclosure (Codex, Cursor, Gemini CLI, raw API calls).
#
# Usage: scripts/build_portable.sh [output_path]
#        defaults to dist/bug-hunt.flat.md

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SKILL="$ROOT/skills/deep-bug-hunter"
OUT="${1:-$ROOT/dist/bug-hunt.flat.md}"
mkdir -p "$(dirname "$OUT")"

{
  echo "<!-- GENERATED by scripts/build_portable.sh — edit skills/deep-bug-hunter instead -->"
  echo "<!-- built $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
  echo

  # SKILL.md without the YAML frontmatter (meaningless to agents without a skill loader)
  awk 'BEGIN{n=0} /^---$/{n++; next} n>=2' "$SKILL/SKILL.md"

  echo
  echo "---"
  echo
  echo "# Appendix: reference material"
  echo
  echo "The workflow above refers to these files. They are inlined here because this"
  echo "build targets agents that load their whole instruction set up front."
  echo

  for f in "$SKILL"/references/*.md; do
    echo
    echo "<!-- from references/$(basename "$f") -->"
    echo
    # Demote headings one level so they nest under the appendix
    sed 's/^#/##/' "$f"
    echo
  done
} > "$OUT"

WORDS=$(wc -w < "$OUT")
echo "wrote $OUT"
echo "~$WORDS words (~$((WORDS * 4 / 3)) tokens) — this loads on every invocation"
echo
echo "If that's too heavy for your agent's context budget, drop the stack checklist"
echo "you don't need: comment out the relevant reference file in this script."
